import type { Metadata } from "next";
import "./globals.css";
import ConditionalHeader from './components/ConditionalHeader'
import Footer from './components/Footer'

export const metadata: Metadata = {
  title: "EventQuest",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`antialiased`}
      >
        <ConditionalHeader />

        <main>
          {children}
        </main>
        
        <Footer/>
      </body>
    </html>
  );
}
